#微信相关配置
wx:
  miniapp:
    appid: wx537a618967b5ffa5
    secret: e7d854cc241187155591f3dd1fae499c
    token: e6170e0539b8bd0e429f4dc5d8fc5eff
    aesKey: Dx5LcP76CvL0JOE5jmqjNExAV2uAYIwhgbpv390itN7
    msgDataFormat: JSON

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.hj.tj.gohome.entity

auth:
  jwt:
    secret: ed92792d87d629d84cf589c5acfe257f
    expire: 2592000
    header: 22f4830ec0a499683c117136444bb6b6

#默认使用配置
spring:
  profiles:
    active: dev


logging:
  config: classpath:logback.xml
server:
  port: 8081
  servlet:
    context-path: gohomeapp

---
#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/gohome?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 821075358q
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

---
#测试配置
spring:
  profiles: test

  datasource:
    url: jdbc:mysql://cdb-96qh7ip0.cd.tencentcdb.com:10022/gohome_test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: huijia931
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


---
#线上配置
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://cdb-96qh7ip0.cd.tencentcdb.com:10022/gohome?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: huijia931
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
