#微信相关配置
wx:
  miniapp:
    configs:
        - appid: wx537a618967b5ffa5
          secret: e7d854cc241187155591f3dd1fae499c
          token: e6170e0539b8bd0e429f4dc5d8fc5eff
          aesKey: Dx5LcP76CvL0JOE5jmqjNExAV2uAYIwhgbpv390itN7
          msgDataFormat: JSON


auth.jwt.secret: ed92792d87d629d84cf589c5acfe257f
auth.jwt.expire: 2592000
auth.jwt.header: 22f4830ec0a499683c117136444bb6b6

#默认使用配置
spring:
  profiles:
    active: dev

mybatis:
  typeAliasesPackage: com.hj.tj.gohome.entity
  mapperLocations: classpath:mapper/*.xml

---
#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gohome
    username: root
    password: 821075358q
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  config: classpath:logback.xml
server:
  port: 8080

